# Default values for nginx-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
namespace: dev

image:
  repository: devregistry0001.azurecr.io/hello_docker
  pullPolicy: IfNotPresent
  tag: latest

backend:
  container:
    port: 8080

imagePullSecrets:
  - name: acr-auth

serviceExternal:
  type: LoadBalancer
  servicePort: 5000