# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
namespace: dev

image:
  repository: demodevregistry0001.azurecr.io/hello_docker
  pullPolicy: Always
  tag: latest

backend:
  container:
    port: 8080

serviceExternal:
  type: LoadBalancer
  servicePort: 5000

envSecrets:
  COSMOSDB_ENDPOINT: cosmoEndpoint
  TEST: test

