apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-docker.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "hello-docker.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hello-docker.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "hello-docker.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.container.port }}
          volumeMounts:
            - name: aks-vault-secrets
              mountPath: "/mnt/aks-vault-secrets"
              readOnly: true
          env:
            {{ range $envVar, $secretName := .Values.envSecrets }}
            - name: {{ $envVar }}
              valueFrom:
                secretKeyRef:
                  name: aks-vault-secret
                  key: {{ $secretName }}
            {{ end }}
      volumes:
        - name: aks-vault-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aks-vault"