apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-docker.fullname" . }}-{{ "public" }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "hello-docker.name" . }}
  type: {{ .Values.serviceExternal.type }}
  ports:
  - port: {{ .Values.serviceExternal.servicePort }}
    targetPort: {{ .Values.backend.container.port }}