apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-docker.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "hello-docker.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.serviceInternal.servicePort }}
      targetPort: {{ .Values.serviceInternal.backendPort }}
